import {MigrationInterface, QueryRunner} from "typeorm";

export class initdev1644327214277 implements MigrationInterface {
    name = 'initdev1644327214277'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "adminConfig" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "module" character varying(300) NOT NULL, "key" character varying(300) NOT NULL, "value" character varying(300) NOT NULL, "context" character varying(300) NOT NULL, "contextId" uuid NOT NULL, "canOverride" boolean NOT NULL, CONSTRAINT "PK_75f61b02cff1011090c0f04ce51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "schoolId" character varying NOT NULL, "userId" character varying NOT NULL, "groupId" character varying NOT NULL, "topicId" character varying, "eventId" character varying, "date" date NOT NULL, "attendance" character varying(20) NOT NULL, "remark" character varying(100), "approved" character varying(10), "approvedBy" character varying(50), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "module" character varying(300) NOT NULL, "key" character varying(300) NOT NULL, "value" character varying(300) NOT NULL, "context" character varying(300) NOT NULL, "contextId" character varying NOT NULL, "canOverride" boolean NOT NULL, CONSTRAINT "PK_d0ee79a681413d50b0a4f98cf7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "schoolId" character varying(300) NOT NULL, "name" character varying(300) NOT NULL, "type" character varying(300) NOT NULL, "status" character varying(300) NOT NULL, CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groupMembership" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "schoolId" character varying NOT NULL, "userId" character varying NOT NULL, "role" character varying(300) NOT NULL, "groupId" uuid, CONSTRAINT "PK_03ac2e09ae6b88222461118f9da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "holiday" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "remark" character varying(300) NOT NULL, "year" character varying NOT NULL, "context" character varying(300) NOT NULL, "contextId" character varying NOT NULL, CONSTRAINT "PK_3e7492c25f80418a7aad0aec053" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "schoolId" character varying NOT NULL, "name" character varying(300) NOT NULL, "start" TIMESTAMP WITH TIME ZONE NOT NULL, "end" TIMESTAMP WITH TIME ZONE NOT NULL, "recurring" boolean NOT NULL, "recurringFrequency" character varying(300) NOT NULL, "groupId" character varying NOT NULL, "topicId" character varying NOT NULL, "creatorId" character varying NOT NULL, "primaryUserId" character varying NOT NULL, "status" character varying(300) NOT NULL, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "name" character varying(300) NOT NULL, CONSTRAINT "PK_57836c3fe2f2c7734b20911755e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "topic" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "createdBy" character varying, "updatedOn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedy" character varying, "schoolId" character varying NOT NULL, "name" character varying(300) NOT NULL, "category" character varying(300) NOT NULL, "status" character varying(300) NOT NULL, CONSTRAINT "PK_33aa4ecb4e4f20aa0157ea7ef61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "groupMembership" ADD CONSTRAINT "FK_edafb569f217f354e1aaac2d4a4" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "groupMembership" DROP CONSTRAINT "FK_edafb569f217f354e1aaac2d4a4"`);
        await queryRunner.query(`DROP TABLE "topic"`);
        await queryRunner.query(`DROP TABLE "school"`);
        await queryRunner.query(`DROP TABLE "event"`);
        await queryRunner.query(`DROP TABLE "holiday"`);
        await queryRunner.query(`DROP TABLE "groupMembership"`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP TABLE "config"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "adminConfig"`);
    }

}
