FROM --platform=linux/amd64 node:16 as build
WORKDIR /app
RUN chmod 777 -R /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build && npm prune --production


FROM --platform=linux/amd64 node:16 as sandbox 
ARG NODE_ENV=sandbox
ENV NODE_ENV=${NODE_ENV}

# Docker working directory
WORKDIR /app
RUN chmod 777 -R /app
COPY --from=build /app/ /app/
EXPOSE 9229
CMD ["node", "dist/main.js"]